[IG]
ig = fsh-generated/resources/ImplementationGuide-fhir.kenyaPSIG.json
; template = fhir.base.template#current
template = local-template
; css-extras = input/includes/custom.css
; suppress-local-dir=true

