CodeSystem: KPSDataElementsCS
Id: kps-data-elements
Title: "KPS Data Element Identifiers"
Description: "Kenya Patient Summary logical data element identifiers referenced by the logical models published in this implementation guide. This fragment intentionally includes the subset of identifiers used in the IG so generated definitional-code links resolve to concrete concepts."
* ^status = #active
* ^experimental = false
* ^caseSensitive = true
* ^content = #fragment

// KPS.A Client Registration
* #KPS.A.DE.1 "Identifier" "Government-issued identifier used to distinguish individuals, e.g., National ID (adults) or Birth Certificate number (under 18)"
* #KPS.A.DE.2 "Name Given" "Client's first name"
* #KPS.A.DE.3 "Name Family" "Client's family name or last name"
* #KPS.A.DE.4 "Date of Birth" "Client's date of birth, if known"
* #KPS.A.DE.5 "Sex" "Sex of the client assigned at birth"
* #KPS.A.DE.8 "Address Country" "Name of country of affiliation"
* #KPS.A.DE.9 "Address County" "County where the client resides"
* #KPS.A.DE.10 "Address Subcounty" "Subcounty of residence"
* #KPS.A.DE.11 "Address Ward" "Ward where the client lives"
* #KPS.A.DE.12 "Address Village" "Village or estate of residence"
* #KPS.A.DE.13 "Address Postal Address" "Mailing address including P.O. Box, street or building details"
* #KPS.A.DE.14 "Telecom Phone" "Phone number (mobile or landline)"
* #KPS.A.DE.15 "Telecom Email" "Email address"
* #KPS.A.DE.16 "Contact Person Role" "Role: legal guardian, next of kin, or other"
* #KPS.A.DE.20 "Contact Person Relationship" "Relationship to the client (e.g., father, spouse, daughter)"
* #KPS.A.DE.21 "Contact Person Name Given" "First name of contact person"
* #KPS.A.DE.22 "Contact Person Name Family" "Surname of contact person"
* #KPS.A.DE.23 "Contact Person Phone" "Phone number of contact person"
* #KPS.A.DE.24 "Contact Person Email" "Email of contact person"
* #KPS.A.DE.26 "Insurance Number" "Health insurance ID assigned to the client"

// KPS.B Clinical Consultation
* #KPS.B.DE.1 "Allergy Allergen" "Substance or agent triggering the reaction"
* #KPS.B.DE.25 "Allergy Propensity Type" "Allergy, intolerance, or unknown"
* #KPS.B.DE.29 "Allergy Description" "Text description of the allergy or intolerance"
* #KPS.B.DE.66 "Allergy Severity" "Severity of the clinical manifestation of the allergic reaction."
* #KPS.B.DE.70 "Allergy Criticality" "Risk of future life-threatening adverse reactions"
* #KPS.B.DE.71 "Allergy Onset Date" "Date the allergy was observed"
* #KPS.B.DE.72 "Allergy Onset Age" "Age at onset of the allergy"
* #KPS.B.DE.73 "Allergy End Date" "Date of resolution of the allergy"
* #KPS.B.DE.74 "Allergy Status" "Current status of the allergy"
* #KPS.B.DE.78 "Allergy Certainty" "Certainty about the reaction's presence"
* #KPS.B.DE.83 "Medical Alert Description" "Description of the alert"
* #KPS.B.DE.84 "Medical Alert Code" "Priority level"
* #KPS.B.DE.88 "Medical Alert Status" "Alert status (active/inactive/etc)"
* #KPS.B.DE.93 "Resolved Problem Description" "Problem or diagnosis"
* #KPS.B.DE.94 "Resolved Problem Onset Date" "Date of problem onset"
* #KPS.B.DE.96 "Resolved Problem End Date" "Resolution date"
* #KPS.B.DE.97 "Resolved Problem Resolution Circumstances" "How the problem was resolved"
* #KPS.B.DE.98 "Medical History" "Narrative or synthesized summary of the client's medical background"
* #KPS.B.DE.99 "Current Problem Condition" "Problem or diagnosis"
* #KPS.B.DE.102 "Current Problem Clinical Status" "Clinical state (active, recurrence, relapse)"
* #KPS.B.DE.106 "Current Problem Verification Status" "Certainty of diagnosis (confirmed, differential)"
* #KPS.B.DE.110 "Current Problem Condition Category" "Problem list or encounter diagnosis"
* #KPS.B.DE.111 "Current Problem Condition Encounter" "Encounter when the condition was first recorded"
* #KPS.B.DE.113 "Current Problem Severity" "Clinical severity"
* #KPS.B.DE.117 "Current Problem Body Site" "Anatomical location"
* #KPS.B.DE.118 "Current Problem Onset Date" "Date of onset"
* #KPS.B.DE.119 "Current Problem Onset Age" "Age at onset"
* #KPS.B.DE.120 "Current Problem Assertion Status" "Assertion about diagnosis certainty"
* #KPS.B.DE.121 "Social History Observation" "Social history observation"
* #KPS.B.DE.122 "Social History Reference Period" "Time period of observation"
* #KPS.B.DE.123 "Pregnancy Status" "Pregnancy status"
* #KPS.B.DE.127 "Pregnancy Status Observation Date" "Date of pregnancy observation"
* #KPS.B.DE.128 "Pregnancy Status Expected Delivery Date" "Estimated due date"
* #KPS.B.DE.129 "Previous Pregnancy Status" "Has the client been pregnant before?"
* #KPS.B.DE.133 "Previous Pregnancy Outcome" "Pregnancy outcome"
* #KPS.B.DE.144 "Previous Pregnancy Outcome Date" "Date of pregnancy outcome"
* #KPS.B.DE.145 "Previous Pregnancy Number of Children" "Number of children/fetuses in the pregnancy"
* #KPS.B.DE.146 "Travel History Destination" "Destination of travel"
* #KPS.B.DE.147 "Travel History Period" "Period of travel (entry and departure dates)"

// KPS.C Diagnostics
* #KPS.C.DE.1 "Category" "Diagnostics Category - clinical discipline, department, or diagnostic service"
* #KPS.C.DE.2 "Diagnostic Name" "Exact name or code of the diagnostic request/report (e.g. Lipid Profile)"
* #KPS.C.DE.3 "Request Date" "Date and time of the diagnostic request"
* #KPS.C.DE.4 "Justification" "Reason for diagnostic request, including relevant clinical notes"
* #KPS.C.DE.5 "Status" "Status of the diagnostic request"
* #KPS.C.DE.13 "Specimen Type" "Type of material collected for analysis"
* #KPS.C.DE.14 "Specimen Availability Status" "Specimen availability status"
* #KPS.C.DE.18 "Imaging Study Type" "Type of imaging study requested (e.g. XR Lumbar spine)"
* #KPS.C.DE.19 "Imaging Date" "Date when imaging was performed"
* #KPS.C.DE.20 "Imaging Body Site" "Body part observed"
* #KPS.C.DE.21 "Imaging Images" "References or links to image series from imaging"
* #KPS.C.DE.22 "Results Date" "Date and time of result availability"
* #KPS.C.DE.23 "Performer" "Name or code of diagnostics performer (originator of result)"
* #KPS.C.DE.24 "Interpreter" "Interpreter of result or validator"
* #KPS.C.DE.25 "Diagnostic Results" "Results from the analysis, e.g. numeric value, boolean, or description"
* #KPS.C.DE.26 "Interpretation" "Interpretation of diagnostic results (e.g. normal, high, low)"
* #KPS.C.DE.27 "Clinical Impression" "Working diagnosis or clinical hypothesis based on diagnostics"

// KPS.D Treatment
* #KPS.D.DE.1 "Medication Reason" "Reason for prescribing or using the medication. May link to past/current conditions."
* #KPS.D.DE.2 "Intended Use" "Indication for use: prevention, treatment, diagnostic, anaesthesia, equipment care."
* #KPS.D.DE.3 "Medication Code" "Medication that was or is to be administered (coded)."
* #KPS.D.DE.4 "Active Ingredient" "Active substance in the medication (e.g. paracetamol)."
* #KPS.D.DE.5 "Strength" "Content of active ingredient per dosage unit (e.g. 500 mg/tablet)."
* #KPS.D.DE.7 "Dosage Regimen" "Dosage instructions: quantity, frequency, and duration (e.g. 1 tab every 24h for 10 days)."
* #KPS.D.DE.8 "Route of Administration" "Path of administration (e.g. oral, intravenous)."
* #KPS.D.DE.9 "Treatment Start Date" "Date to start the treatment or medication."
* #KPS.D.DE.10 "Plan of Care" "Therapeutic recommendations excluding medication: diet, surgery, exercise, etc."
* #KPS.D.DE.11 "External Reference" "External reference to guidelines or other clinical knowledge."
* #KPS.D.DE.12 "Related With" "Link to related entries in the Patient Summary (e.g. rare disease)."

// KPS.E Immunization
* #KPS.E.DE.1 "Target Disease" "Disease or agent that the vaccination provides protection against"
* #KPS.E.DE.1.1 "Status" "Current status of immunization against the disease"
* #KPS.E.DE.2 "Vaccine Prophylaxis" "Generic description of the vaccine/prophylaxis or its component(s)"
* #KPS.E.DE.3 "Vaccine Brand" "Brand name of the vaccine medicinal product"
* #KPS.E.DE.4 "Vaccine Identifier" "Identifier for the vaccine medicinal product (e.g. MPID, EMA PMS ID, or national ID)"
* #KPS.E.DE.5 "Marketing Authorisation Holder" "Organization or individual authorized to market the vaccine"
* #KPS.E.DE.6 "Dose Number" "Order in the vaccination course"
* #KPS.E.DE.7 "Lot Number" "Specific identifier of the vaccine batch"
* #KPS.E.DE.8 "Vaccination Date" "Date when the vaccination was administered"
* #KPS.E.DE.8.1 "Age at Vaccination" "Age at which the vaccination was administered"
* #KPS.E.DE.9 "Administering Centre" "Name or code of the administering centre or health authority"
* #KPS.E.DE.10 "Health Professional" "Name or code of the health professional who administered the vaccine"
* #KPS.E.DE.12 "Next Vaccination Date" "Date of the planned next vaccination (e.g. next dose)"
